services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joseclevina
      MYSQL_DATABASE: appointments_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: mysql://root:joseclevina@db:3306/appointments_db
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

volumes:
  mysql_data:
