// permissions.ts
export const PERMISSIONS = {
  GERENCIAR_UTILIZADORES: "GERENCIAR_UTILIZADORES",
  GERENCIAR_UTENTES: "GERENCIAR_UTENTES",
  GERENCIAR_SERVICOS: "GERENCIAR_SERVICOS",
  GERENCIAR_MARCACOES: "GERENCIAR_MARCACOES",
  GERENCIAR_HORARIOS: "GERENCIAR_HORARIOS",
  VISUALIZAR_RELATORIOS: "VISUALIZAR_RELATORIOS",
  GERAR_RELATORIO: "GERAR_RELATORIO",
  GERENCIAR_PERMISSOES: "GERENCIAR_PERMISSOES",
  GERENCIAR_FUNCOES: "GERENCIAR_FUNCOES",
};