import { PERMISSIONS } from "./permissions";

export const ROLES = {
  ADMIN: Object.values(PERMISSIONS),
  SECRETARIA: [
    PERMISSIONS.GERENCIAR_UTENTES,
    PERMISSIONS.GERENCIAR_MARCACOES,
    PERMISSIONS.GERENCIAR_SERVICOS,
  ],
  MEDICO: [
    PERMISSIONS.GERENCIAR_MARCACOES,
    PERMISSIONS.GERENCIAR_HORARIOS,
    PERMISSIONS.VISUALIZAR_RELATORIOS,
  ],
  // ...outras funções
};